
name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: Test
        run: |
          ls
          pwd

      - name: Reset GitHub Actions Cache
        run: sudo rm -rf /usr/local/actions/cache || true

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: application-jelly.properties 생성
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application-jelly.properties

      - name: Gradle 빌드
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: EC2에 파일 전송 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/oneteam-BE/tobe

      - name: EC2에 배포 (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/oneteam-BE/current
            mkdir /home/ubuntu/oneteam-BE/current
            mv /home/ubuntu/oneteam-BE/tobe/project.jar /home/ubuntu/oneteam-BE/current/project.jar
            cd /home/ubuntu/oneteam-BE/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/oneteam-BE/tobe

